// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyKdYqXji_StobpD6H38evt5WOZgz178',
    appId: '1:292018054397:web:5c50b9a0f3290b96838a94',
    messagingSenderId: '292018054397',
    projectId: 'campus-book-exchange-c48e0',
    authDomain: 'campus-book-exchange-c48e0.firebaseapp.com',
    databaseURL: 'https://campus-book-exchange-c48e0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-book-exchange-c48e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgZcW6TcbOKsFTgjeY37MnbyWlmkse6Y',
    appId: '1:292018054397:android:c99e84f7c14dbcea838a94',
    messagingSenderId: '292018054397',
    projectId: 'campus-book-exchange-c48e0',
    databaseURL: 'https://campus-book-exchange-c48e0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-book-exchange-c48e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyTLoFBOcJB8ea8HXfoba9uAOP5ew0WQ',
    appId: '1:292018054397:ios:ea3bbaabef17855b838a94',
    messagingSenderId: '292018054397',
    projectId: 'campus-book-exchange-c48e0',
    databaseURL: 'https://campus-book-exchange-c48e0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-book-exchange-c48e0.firebasestorage.app',
    iosBundleId: 'com.example.campusBookExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyTLoFBOcJB8ea8HXfoba9uAOP5ew0WQ',
    appId: '1:292018054397:ios:ea3bbaabef17855b838a94',
    messagingSenderId: '292018054397',
    projectId: 'campus-book-exchange-c48e0',
    databaseURL: 'https://campus-book-exchange-c48e0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-book-exchange-c48e0.firebasestorage.app',
    iosBundleId: 'com.example.campusBookExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFyKdYqXji_StobpD6H38evt5WOZgz178',
    appId: '1:292018054397:web:82f7229f44d54d77838a94',
    messagingSenderId: '292018054397',
    projectId: 'campus-book-exchange-c48e0',
    authDomain: 'campus-book-exchange-c48e0.firebaseapp.com',
    databaseURL: 'https://campus-book-exchange-c48e0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-book-exchange-c48e0.firebasestorage.app',
  );
}
